services:
  wiremock:
    build:
      context: .
      dockerfile: Dockerfile
    image: nikozone-wiremock-demo:latest
    restart: unless-stopped
    ports:
      - "${WIREMOCK_API_PORT:-8088}:8089"
      - "${WIREMOCK_GUI_PORT:-8087}:8080"
    command: --port 8089 --global-response-templating --verbose --max-request-journal 1000

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "${MAILHOG_SMTP_PORT:-1025}:1025"
      - "${MAILHOG_UI_PORT:-8025}:8025"